### ISSUE TITLE
Docs FAQ content

### ISSUE THREAD

**Issue by p5150j** [ProjectLibertyLabs/gateway#213]
As a user I would like to have a docs FAQs page.

FAQ:

- Answers to frequently asked questions about using Frequency, blockchain concepts, and migration processes.

Please see master outline here
https://docs.google.com/document/d/1ZU968cvrR8eXjwP0vGFacUO_SCY901fRUPAD5dKruNg/edit#heading=h.t0m9wx7fa5dk

**Comment by wilwade** [comment]
Not for now.
