### ISSUE TITLE
Microservices that use a webhook should replace PROVIDER_BASE_URL with WEBHOOK_BASE_URL

### ISSUE THREAD

**Issue by mattheworris** [ProjectLibertyLabs/gateway#218]
## Description
The gateway microservices that use webhooks previously used the environment variable `PROVIDER_BASE_URL` as the webhook target server. The `social-app-template` has adopted a new nomenclature using `WEBHOOK_BASE_URL`. All micro services should be in sync with the `social-app-template` and use the new nomenclature.

## Acceptance Criteria

All microservices that use webhooks use `WEBHOOK_BASE_URL` to provision their webhook.
- [ ] #350 
- [x] #355
- [x] content-watcher
- [ ] #356

Follow up to remove entirely: https://github.com/ProjectLibertyLabs/gateway/issues/339

**Comment by JoeCap08055** [comment]
Actually, `WEBHOOK_BASE_URL` in SAT is meant to be used with services that allow for webhook registration _a la_ `content-watcher`. Any Gateway services currently using a statically-configured webhook should instead adopt an ability to dynamically register webhooks.
