### ISSUE TITLE
Docs: All OpenAPI Services into a Single API Reference Section

### ISSUE THREAD

**Issue by p5150j** [ProjectLibertyLabs/gateway#229]
Title: Combine All OpenAPI Services into a Single API Reference Section

Description:
Create a combined API reference section that includes the OpenAPI definitions for all services (Account, Content Publisher, Content Watcher, and Graph). Embed this combined OpenAPI page into the documentation site.

Tasks:

- [ ] Gather the OpenAPI definitions for all services.
- [ ] Combine the OpenAPI definitions into a single OpenAPI document.
- [ ] Embed the combined OpenAPI document into a new API Reference section of the documentation site.
- [ ] Ensure the combined API reference is easily navigable and includes clear explanations and usage examples.

Acceptance Criteria:

- A new API Reference section exists in the documentation site.
- The API Reference section includes the combined OpenAPI definitions for all services.
- The documentation is clear, well-organized, and includes examples and explanations for using the APIs.

**Comment by wilwade** [comment]
Not sure we want/need this anymore. Closing for now.
