### ISSUE TITLE
all-services: Notification queue should unpause based on capacity refilled event

### ISSUE THREAD

**Issue by mattheworris** [ProjectLibertyLabs/gateway#267]
# Goal
The goal of this issue is to update the logic gating the pause of the notification queue when capacity is exhausted. Currently, exhausted capacity results in the queue being paused for a timeout equal to the epoch time. 

However, it should be possible to detect when capacity has been replenished and automatically resume the queue.
See `reconnection-service` or `content-publishing-service` for alternate implementations that may be useful.

## Acceptance Criteria

- [ ] Paused queues are re-enabled when capacity is replenished and do not wait for a the entire epoch timeout.

**Comment by wilwade** [comment]
@mattheworris Did this happen?

**Comment by mattheworris** [comment]
No, still a todo.
