### ISSUE TITLE
Announcement types should come from a package/be exported to OpenApi spec

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/gateway#273]
# Description
Currently, the announcement types for determining which webhooks to invoke for a given announcement come from a locally-defined enum, with hard-coded strings (which are lowercased in some places for comparison, but not all). As a developer, these announcement types should come from a single source of truth (ideally a DSNP-provided package), and be propagated to downstream consumers of the API.

# Acceptance Criteria
- [ ] `AnnouncementType` enum should come from a DSNP package, if possible. (Or perhaps not an enum at all... as schemas are not necessarily always going to be a fixed set defined by DSNP.)
- [x] Any range of string/enum used to register an announcement type for a webhook should be properly exposed in the generated OpenAPI spec document so that it can be imported by a client

**Comment by wilwade** [comment]
Might be coming from DSNP soon

**Comment by wilwade** [comment]
Closing for now. It is now consistent inside of Gateway
