### ISSUE TITLE
Restore endpoint DTO validation check for content hash & DSNP content URI

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/gateway#352]
# Description
Due to some ongoing confusion/discussion/bugs regarding the calculation & encoding of content hashes & DSNP URIs, a check was disabled in `content-publishing` in order to allow Gateway services posts to work. The underlying issues have now been resolved, and so we should restore the _correct_ validation to the API endpoints.

The validation is peformed by decorators in [this file](https://github.com/ProjectLibertyLabs/gateway/blob/main/services/content-publishing/libs/common/src/utils/dsnp-validation.decorator.ts)

**Comment by wilwade** [comment]
Is this a duplicate of https://github.com/ProjectLibertyLabs/gateway/issues/276?
