### ISSUE TITLE
Review: Blockchain scanning use cases

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/gateway#376]
# Description
As a developer of Gateway, I want a standard way to monitor the blockchain for events of interest. There are a number of use cases that should be covered:

1. Always monitor "current" new blocks as they are formed, to provide timely event notifications to subscribers when things happen on-chain. If the scanning app restarts, it should always resume at the current end-of-chain. Consumers may not care about past missed content; are more concerned with "current" new content.
2. Continuously "crawl" the chain from an initial point as new blocks are formed. If the scanning app restarts, resume scanning at the point at which scanning last left off. Consumers are less concerned about timely notification of new events, and more concerned about not missing any notifications.
3. Dynamically "crawl" the chain for some user-defined block range.
4. (kind of a mash-up of 1/2/3, but specifically for tracking the completion status of an extrinsic submitted at Block X with mortality at Block Y)

Notes:
1 & 2, for a long-running app, should appear similar, inasmuch as in the best-case scenario they should both be scanning the same block (current end-of-chain). There is perhaps some achievable optimization here to eliminate duplicate work in that case.

(thinking out loud here): Would it be more efficient, instead of having blockchain scanner logic inside each Gateway service, to have a central chain-scanning service feeding the other Gateway services via a pub/sub or other queueing mechanism?

**Comment by wilwade** [comment]
Not needed for now.
