### ISSUE TITLE
`applyItemActions` (for graph encryption key management)

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/gateway#414]
# Description
As a Provider/consumer of the Gateway API, I want to be able to manage encryption keys for a user (for Private Graph, or any other purpose). This particular endpoint should be specific to the dsnp private graph encryption key

See @claireolmstead's prs for a pattern

# Discussion
- Which version(s) of this extrinsic to support--signed, delegated, or both?
    - Signed only
- Does this belong in `account` or `graph` service?
    - `account` service

**Comment by p5150j** [comment]
per @wilwade 

Account service key mngt and signed by user.
