### ISSUE TITLE
Review RPC and state query support for Gateway

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/gateway#416]
# Description
The SaaS team would like to sunset their JVM-based API in favor of using Gateway services. Review the following "get" methods for support in the Gateway API. Any methods that are determined to require implementation in the Gateway API should be converted to sub-tasks; otherwise, they should be marked complete.

- [x] ~getGenesisBlockHashHex()~
- [x]  ~getFinalizedHeadBlockHashHex()~
- [x]  ~getFinalizedHeadBlockNumber()~
- [x] ~getLastBlockNumber()~
- [x] getHealth()
- [x] getMsaIdByAccountId(publicKeyByteArray: ByteArray)
- [x] ~getRuntimeVersion(blockHashHex: String? = null)~
- [x] ~getAccountNonce(publicKeyBytes: ByteArray)~
- [x] ~getMessages(schemaId: Int, blockPaginationRequest: BlockPaginationRequest)~
- [x] ~getItemizedStorage(msaId: BigInteger, schemaId: Int)~
- [x] ~getPaginatedStorage(msaId: BigInteger, schemaId: Int)~
- [x] ~getEvents(blockHashHex: String)~
- [x] getHandle(msaId: BigInteger)
- [x] getNextSuffixes(handle: String, count: Int)
- [x] #503
- [x] #504
- [x] getCapacityBalance(msaId: BigInteger)
- [x] ~currentNonce()~

**Comment by p5150j** [comment]
@JoeCap08055 to trim down what is already supported and or not useful
