### ISSUE TITLE
[bug] Nonce service should be a singleton across Gateway

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/gateway#417]
# Description
Each Gateway service makes use of a `NonceService` class that utilizes Redis to keep track of submitted extrinsics & nonce usage, so that multiple extrinsic submissions in a short period of time don't fall afoul of either duplicate nonces or holes in the nonce.

Because each service uses the same keypair/seed phrase, the Redis key used for the NonceService should be common across the services; currently the service-specific key prefix applies to the nonce service keys as well, which makes it more likely that the services could encounter nonce problems.

The key used should incorporate the public key of the provisioned keypair, as nonces are tied to a public key, not an MSA.

**Comment by p5150j** [comment]
@JoeCap08055 prefix by pub key
