### ISSUE TITLE
Generate webhook request and response datatypes from OpenAPI spec document.

### ISSUE THREAD

**Issue by mattheworris** [ProjectLibertyLabs/gateway#457]
# Goal
The goal of this issue is to generate data type objects from the account-service OpenAPI spec.

# Acceptance Criteria

- [ ] Webhook Request and Response data types are generated from spec.
- [ ] Generated types are used in the implementation.
- [ ] ~DTO Validations are added as needed.~

**Comment by JoeCap08055** [comment]
Note, `graph-service` and `content-watcher-service` already do this; `account-service` should follow the same approach.
