### ISSUE TITLE
Cloud Secrets Management

### ISSUE THREAD

**Issue by p5150j** [ProjectLibertyLabs/gateway#475]
As a security engineer,
I want to implement Cloud Secrets Manager for managing sensitive data like IPFS pinning API keys, passwords, and seed phrases, so that I can securely store, access, and manage secrets required by the Gateway stack.

Acceptance Criteria:

- Cloud Secrets Manager should be configured to store sensitive data such as API keys, passwords, and seed phrases.
- Secrets should be encrypted and access-controlled based on roles and permissions.
- The application should be able to retrieve secrets securely from Cloud Secrets Manager.
- README Documentation on how to manage secrets should be provided.

Note:
Development teams need to add and relate all necessary implementation subtasks (e.g., integrating AWS Secrets Manager with the application, setting up access controls, encrypting secrets) to this story for comprehensive tracking.

**Comment by saraswatpuneet** [comment]
added a support path for Hashicorp Vault
