### ISSUE TITLE
Faucet Design

### ISSUE THREAD

**Issue by p5150j** [ProjectLibertyLabs/gateway#479]
### **Implement the new Frequency Faucet Interface design**

**As a** front-end developer,  
**I want to** implement the new Frequency Faucet interface design,  
**so that** users can request test tokens easily and securely, while maintaining design consistency with the Frequency guidelines.

**Acceptance Criteria:**
- Develop the user interface for the Frequency Faucet that aligns with the [Frequency Style Guidelines](https://www.figma.com/design/EjFt1XdacOogDZoQ7RetrI/Frequency-Style-Guidelines?node-id=25-32&t=pFC8eElSnqm40ms5-0) provided in Figma.
- Ensure that the interface allows users to seamlessly request and receive test tokens.
- Replace reCAPTCHA with hCaptcha to enhance security and improve user experience.
- Ensure that the design and user interface are consistent with the style guide available at: [Frequency Style Guidelines on Figma](https://www.figma.com/design/EjFt1XdacOogDZoQ7RetrI/Frequency-Style-Guidelines?node-id=25-32&t=pFC8eElSnqm40ms5-0).
- The development process should utilize resources and code available at the provided links: [Testnet Faucet: Live Faucet](https://faucet.testnet.frequency.xyz/) and [Source Code: GitHub Repository](https://github.com/frequency-chain/testnet-faucet).

**Note:**
- There are no new mocks available for this task. **The existing UI and UX should be maintained while reskinning the interface to align with the Frequency Style Guidelines** as linked in the Figma file.
- **Development teams need to add and relate all necessary implementation subtasks** (e.g., creating UI components, integrating hCaptcha, ensuring API connectivity, aligning with style guidelines) to this story to ensure a comprehensive and well-managed implementation process.

Sub tasks

- [x] https://github.com/frequency-chain/testnet-faucet/issues/18
- [x] https://github.com/frequency-chain/testnet-faucet/issues/22
- [x] https://github.com/frequency-chain/testnet-faucet/issues/17
- [x] https://github.com/frequency-chain/testnet-faucet/issues/21
- [x] https://github.com/frequency-chain/testnet-faucet/issues/20
- [x] https://github.com/frequency-chain/testnet-faucet/issues/19

**Comment by claireolmstead** [comment]
Track the progress and add issues in the [Testnet Faucet Project](https://github.com/orgs/frequency-chain/projects/2/views/1).
