### ISSUE TITLE
Provider Dashboard Design

### ISSUE THREAD

**Issue by p5150j** [ProjectLibertyLabs/gateway#480]
### **Reskin the Provider Dashboard**

**Objective:**  
Reskin the existing Provider Dashboard to adhere to the design and style guidelines provided in the Frequency Style Guide.

**As a** front-end developer,  
**I want to** reskin the existing Provider Dashboard,  
**so that** the interface maintains a user-friendly experience while aligning with the Frequency design guidelines.

**Acceptance Criteria:**
- Update the visual elements of the existing Provider Dashboard, including fonts, colors, buttons, and layouts, to match the [Frequency Style Guidelines](https://www.figma.com/design/EjFt1XdacOogDZoQ7RetrI/Frequency-Style-Guidelines?node-id=25-32&t=pFC8eElSnqm40ms5-0).
- Ensure the dashboard's design is consistent with the style guide available at: [Frequency Style Guidelines on Figma](https://www.figma.com/design/EjFt1XdacOogDZoQ7RetrI/Frequency-Style-Guidelines?node-id=25-32&t=pFC8eElSnqm40ms5-0).
- The dashboard should continue to provide a seamless, user-friendly interface for providers to manage their services without altering the core functionality.
- Utilize existing resources and code available at: [Provider Dashboard: Live Dashboard](https://provider.frequency.xyz/) and [Source Code: GitHub Repository](https://github.com/frequency-chain/provider-dashboard).

**Note:**
- This task is strictly a reskin. **No new UI/UX changes are required aside from updating the design to align with the Frequency Style Guidelines**.
- **Development teams need to add and relate all necessary implementation subtasks** (e.g., updating CSS, modifying component styles, ensuring adherence to style guidelines) to this story to ensure a smooth reskinning process.

Notes from design:
- Remove the background image
- Background color should be solid branding color primary 
- Cards and nav the dark neutral black  
- Font treatments and sizes to match the style guide 
- Buttons should be the secondary branding color 
- Form elements should match colors, borders (including error states, dropdowns and required fields)
- Additional components not called out in the style guide use your best judgment and infer from the style guide  

Sub tasks

- [x] https://github.com/frequency-chain/provider-dashboard/issues/167
- [x] https://github.com/frequency-chain/provider-dashboard/issues/171
- [x] https://github.com/frequency-chain/provider-dashboard/issues/168
- [x] https://github.com/frequency-chain/provider-dashboard/issues/170
- [x] https://github.com/frequency-chain/provider-dashboard/issues/166
- [x] https://github.com/frequency-chain/provider-dashboard/issues/165
- [x] https://github.com/frequency-chain/provider-dashboard/issues/169
- [x] https://github.com/frequency-chain/provider-dashboard/issues/163

**Comment by claireolmstead** [comment]
Track issues here: https://github.com/orgs/frequency-chain/projects/3/views/1
