### ISSUE TITLE
Need documentation for webhooks

### ISSUE THREAD

**Issue by JoeCap08055** [ProjectLibertyLabs/gateway#487]
# Description
As a client of Gateway services, I want to understand what APIs my services should expose in order to inter-operate fully with various Gateway servives.

We have webhook specifications in separate OpenAPI files from the service REST API specs. The specs for the webhook types and endpoints should also be published with the docs, and some additional documentation added regarding the purpose of the webhooks and the flows they support.

Requested by Odessa.

**Comment by wilwade** [comment]
@JoeCap08055 is this fixed in https://github.com/ProjectLibertyLabs/gateway/pull/523

**Comment by JoeCap08055** [comment]
> @JoeCap08055 is this fixed in #523

Nominally, yes, but something still seems to be missing. Or it might just be because the docs site doesn't update until we cut a new release.
