### ISSUE TITLE
Handle User Redirection and Authorization in Frequency Access

### ISSUE THREAD

**Issue by p5150j** [ProjectLibertyLabs/gateway#525]
### Summary:
As a developer, I want to ensure the app correctly handles user redirection to Frequency Access for authentication and receives the `authorizationCode`, so that the Gateway can process it.

#### Acceptance Criteria:

- The app redirects the user to the `AuthenticationSessionUrl` in a browser or embedded browser.
- Frequency Access manages user authentication and authorization.
- After successful authentication, Frequency Access redirects the user back to the app's callback URL with the `authorizationCode` appended.
- The app captures the `authorizationCode` and sends it to the app backend.

#### Tasks:

1. Implement redirection logic in the app to navigate the user to `AuthenticationSessionUrl`.
2. Handle the callback URL in the app to extract the `authorizationCode`.
3. Send the `authorizationCode` to the app backend.
4. Ensure proper handling in both web and mobile environments (embedded browsers, deep linking, etc.).
5. Write tests to validate the redirection and callback handling.

**Comment by wilwade** [comment]
Verified complete.
