### ISSUE TITLE
Switch to the new versions of the DSNP Schemas

### ISSUE THREAD

**Issue by wilwade** [ProjectLibertyLabs/gateway#555]
With DSNP v1.3 merged and motions on Frequency passed, we need to update to use the newer v1.3 schemas. (STRING version instead of BYTE_ARRAY)

- dsnp.update: 19
- dsnp.reply: 18
- dsnp.tombstone: 16
- dsnp.broadcast: 17

In this case, as the prior schemas are unused on mainnet, we can just switch and ignore prior schema ids or feel free to support both if it is easy to setup (as in the future we will need to support more than one)

- [ ] Update content publisher to use the new schemas
- [ ] Update Frequency Scenario Templates (if needed)
- [ ] Update Content Watcher
- [ ] Update delegations on SAT

Related: https://github.com/frequency-chain/frequency/issues/2176

Motions:
- https://frequency.polkassembly.io/motion/45
- https://frequency.polkassembly.io/motion/46
- https://frequency.polkassembly.io/motion/47
- https://frequency.polkassembly.io/motion/48

**Comment by saraswatpuneet** [comment]
this fix goes in SchemaBuilder, that i think its part of scenario template

**Comment by saraswatpuneet** [comment]
I think we autodetect schemas , I do not see anywhere we set numbers

https://github.com/ProjectLibertyLabs/frequency-scenario-template/blob/441735be68b57f2de14281fc3f990ab5d08a087d/src/scaffolding/schema-builder.ts#L90

**Comment by wilwade** [comment]
@saraswatpuneet  Few questions:

1. Do we need to update our `@dsnp/schema` library and make sure it is using the correct parquet for the correct schema version?
2. When we add `dsnp.broadcast@v3` that takes different data, how do we allow people to continue to use `dsnp.broadcast@v2` until they swap over? (Perhaps this needs to be a separate story?)
3. (perhaps part of 2) Currently if a new version of a schema has a different data structure, we would continue to publish the older version of the data file on the new schema right? We need to make sure that cannot happen.
4. How are we doing the watcher side of things? I see the API doesn't care about version. Currently the announcements are not versioned, but perhaps we need to?

**Comment by saraswatpuneet** [comment]
We can cover those in this story
1. `frequency-scenario-template` was not updated and it is used in graph service, `@dsnp/schemas` and other related libs all :+1: 
2. We can do that in this story,  can we do something in http pre flight checks that can be sort of a warning like a redirect notice?

**Comment by saraswatpuneet** [comment]
Confirming that

> dsnp.update: 19
> dsnp.reply: 18
> dsnp.tombstone: 16
> dsnp.broadcast: 17

are all correct as v2 in gateway

**Comment by wilwade** [comment]
> are all correct as v2 in gateway, we can purge the old version for now? Supporting them and figuring out a procedural way to deprecate would be a good story

Sounds good to me. Thanks for checking on all this
